server:
      port: 8085
spring:
      datasource:
          url: jdbc:oracle:thin:@127.0.0.1:1521:XE
          username: SYSTEM
          password: 1234
          driver-class-name: oracle.jdbc.driver.OracleDriver
      jpa:
        hibernate:
          ddl-auto: create
        properties:
          hibernate:
           format_sql: true
      logging:
        level:
          org.hibernate.SQL: debug
          org.hibernate.type: trace # 실제 들어가는 파라미터값 찍어주는 설정   
#spring-security
      security:
          user:
            name: myPocket
            password: myPocket                   

      profiles:
        include:
          EX-API-KEY