DROP TABLE "EXERCISE";

CREATE TABLE "EXERCISE" (
	"EXERCISE_ID"	NUMBER		NOT NULL,
	"CLASSIFICATION"	VARCHAR		NULL,
	"NAME"	VARCHAR		NULL,
	"GIF"	CLOB		NULL
);

DROP TABLE "MUSCLES";

CREATE TABLE "MUSCLES" (
	"MUSCLE_ID"	NUMBER		NOT NULL,
	"MUSCLE_ABBR"	VARCHAR		NULL,
	"ExerciseID"	NUMBER		NOT NULL
);

DROP TABLE "EQUIPMENT";

CREATE TABLE "EQUIPMENT" (
	"EQUIPMENT_ID"	NUMBER		NOT NULL,
	"NAME"	VARCHAR		NULL,
	"ExerciseID"	NUMBER		NOT NULL
);

DROP TABLE "INSTRUCTIONS";

CREATE TABLE "INSTRUCTIONS" (
	"INSTRUCTION_ID"	NUMBER		NOT NULL,
	"DESCRIPTION"	CLOB		NULL,
	"ExerciseID"	NUMBER		NOT NULL
);

ALTER TABLE "EXERCISE" ADD CONSTRAINT "PK_EXERCISE" PRIMARY KEY (
	"EXERCISE_ID"
);

ALTER TABLE "MUSCLES" ADD CONSTRAINT "PK_MUSCLES" PRIMARY KEY (
	"MUSCLE_ID"
);

ALTER TABLE "EQUIPMENT" ADD CONSTRAINT "PK_EQUIPMENT" PRIMARY KEY (
	"EQUIPMENT_ID"
);

ALTER TABLE "INSTRUCTIONS" ADD CONSTRAINT "PK_INSTRUCTIONS" PRIMARY KEY (
	"INSTRUCTION_ID"
);

ALTER TABLE "MUSCLES" ADD CONSTRAINT "FK_EXERCISE_TO_MUSCLES_1" FOREIGN KEY (
	"ExerciseID"
)
REFERENCES "EXERCISE" (
	"EXERCISE_ID"
);

ALTER TABLE "EQUIPMENT" ADD CONSTRAINT "FK_EXERCISE_TO_EQUIPMENT_1" FOREIGN KEY (
	"ExerciseID"
)
REFERENCES "EXERCISE" (
	"EXERCISE_ID"
);

ALTER TABLE "INSTRUCTIONS" ADD CONSTRAINT "FK_EXERCISE_TO_INSTRUCTIONS_1" FOREIGN KEY (
	"ExerciseID"
)
REFERENCES "EXERCISE" (
	"EXERCISE_ID"
);

